package hook

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

const CommitMsgHook = `#!/bin/sh
# Generated by tagoly install-hook.
set -e

repo_root=$(git rev-parse --show-toplevel 2>/dev/null || pwd)
cd "$repo_root"

exec tagoly lint --message-file "$1"
`

type InstallOptions struct {
	Force bool
}

func InstallCommitMsgHook(workDir string, opts InstallOptions) (string, error) {
	hookPath, err := CommitMsgHookPath(workDir)
	if err != nil {
		return "", err
	}

	if err := WriteCommitMsgHook(hookPath, opts); err != nil {
		return "", err
	}

	return hookPath, nil
}

func CommitMsgHookPath(workDir string) (string, error) {
	cmd := exec.Command("git", "rev-parse", "--git-path", "hooks/commit-msg")
	cmd.Dir = workDir

	out, err := cmd.Output()
	if err != nil {
		return "", fmt.Errorf("failed to resolve git hook path: %w", err)
	}

	hookPath := strings.TrimSpace(string(out))
	if hookPath == "" {
		return "", fmt.Errorf("failed to resolve git hook path")
	}

	if !filepath.IsAbs(hookPath) {
		hookPath = filepath.Join(workDir, hookPath)
	}

	hookPath, err = filepath.Abs(hookPath)
	if err != nil {
		return "", fmt.Errorf("failed to resolve absolute hook path: %w", err)
	}

	return hookPath, nil
}

func WriteCommitMsgHook(hookPath string, opts InstallOptions) error {
	if err := os.MkdirAll(filepath.Dir(hookPath), 0755); err != nil {
		return fmt.Errorf("failed to create hooks directory: %w", err)
	}

	if current, err := os.ReadFile(hookPath); err == nil {
		if string(current) != CommitMsgHook && !opts.Force {
			return fmt.Errorf("commit-msg hook already exists; rerun with --force to overwrite")
		}
	} else if !os.IsNotExist(err) {
		return fmt.Errorf("failed to read existing commit-msg hook: %w", err)
	}

	if err := os.WriteFile(hookPath, []byte(CommitMsgHook), 0755); err != nil {
		return fmt.Errorf("failed to write commit-msg hook: %w", err)
	}

	if err := os.Chmod(hookPath, 0755); err != nil {
		return fmt.Errorf("failed to make commit-msg hook executable: %w", err)
	}

	return nil
}
